const VULNERABILITIES = [
  {
    id: "001",
    name: "SQL Injection",
    codename: "SQLi",
    type: "Injection",
    severity: "Critical",
    pokemonId: 3,
    description: "Malicious SQL code inserted into input fields to manipulate backend databases.",
    found: true,
    writeupUrl: "writeups/sqli.html"
  },
  {
    id: "002",
    name: "Cross-Site Scripting",
    codename: "XSS",
    type: "Client-Side",
    severity: "Medium",
    pokemonId: 6,
    description: "Injection of malicious scripts into web pages viewed by other users.",
    found: true,
    writeupUrl: "writeups/xss.html"
  },
  {
    id: "003",
    name: "Cross-Site Request Forgery",
    codename: "CSRF",
    type: "Logic",
    severity: "Medium",
    pokemonId: 9,
    description: "Forces authenticated users to execute unwanted actions on a web app.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "004",
    name: "Server-Side Request Forgery",
    codename: "SSRF",
    type: "Network",
    severity: "Critical",
    pokemonId: 15,
    description: "Attacker induces the server to make requests to unintended locations.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "005",
    name: "Server-Side Template Injection",
    codename: "SSTI",
    type: "Injection",
    severity: "Critical",
    pokemonId: 18,
    description: "Malicious template directives injected into server-side templates for RCE.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "006",
    name: "XML External Entity",
    codename: "XXE",
    type: "Injection",
    severity: "High",
    pokemonId: 20,
    description: "XML input containing a reference to an external entity processed by a weak parser.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "007",
    name: "Local File Inclusion",
    codename: "LFI",
    type: "Injection",
    severity: "High",
    pokemonId: 22,
    description: "Attacker tricks the application into exposing or running files on the server.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "008",
    name: "Command Injection",
    codename: "CMDi",
    type: "Injection",
    severity: "Critical",
    pokemonId: 28,
    description: "Execution of arbitrary commands on the host OS via vulnerable application.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "009",
    name: "Insecure File Upload",
    codename: "FileUpload",
    type: "Logic",
    severity: "High",
    pokemonId: 149,
    description: "Uploading malicious files (shells, scripts) due to improper validation.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "010",
    name: "GraphQL Vulnerabilities",
    codename: "GraphQL",
    type: "API",
    severity: "High",
    pokemonId: 150,
    description: "Introspection abuse, batching attacks, and authorization bypass in GraphQL APIs.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "011",
    name: "Host Header Injection",
    codename: "HHI",
    type: "Network",
    severity: "Critical",
    pokemonId: 151,
    description: "Manipulating the Host header to poison caches, reset passwords, or redirect.",
    found: true,
    writeupUrl: "writeups/hhi.html"
  },
  {
    id: "012",
    name: "HTTP Request Smuggling",
    codename: "Smuggling",
    type: "Network",
    severity: "Critical",
    pokemonId: 110,
    description: "Exploiting discrepancies in how front-end and back-end servers process HTTP requests.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "013",
    name: "Insecure Deserialization",
    codename: "Deserial",
    type: "Injection",
    severity: "Critical",
    pokemonId: 91,
    description: "Manipulating serialized objects to achieve RCE, authentication bypass, or privilege escalation.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "014",
    name: "JWT Attacks",
    codename: "JWT",
    type: "Auth",
    severity: "High",
    pokemonId: 80,
    description: "Algorithm confusion, weak secrets, and none-algorithm attacks on JSON Web Tokens.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "015",
    name: "NoSQL Injection",
    codename: "NoSQLi",
    type: "Injection",
    severity: "High",
    pokemonId: 42,
    description: "Injection attacks targeting NoSQL databases like MongoDB to bypass auth or exfil data.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "016",
    name: "OAuth Vulnerabilities",
    codename: "OAuth",
    type: "Auth",
    severity: "High",
    pokemonId: 68,
    description: "Flawed OAuth flows enabling account takeover, token theft, and open redirects.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "017",
    name: "Client-Side Prototype Pollution",
    codename: "CSPP",
    type: "Client-Side",
    severity: "Medium",
    pokemonId: 76,
    description: "Polluting JavaScript prototypes via client-side sinks to manipulate app behavior.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "018",
    name: "Server-Side Prototype Pollution",
    codename: "SSPP",
    type: "Injection",
    severity: "High",
    pokemonId: 26,
    description: "Poisoning Node.js object prototypes server-side to achieve RCE or privilege escalation.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "019",
    name: "Web Cache Deception",
    codename: "CacheDeception",
    type: "Logic",
    severity: "High",
    pokemonId: 94,
    description: "Tricking caches into storing sensitive user-specific responses accessible to attackers.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "020",
    name: "Web Cache Poisoning",
    codename: "CachePoisoning",
    type: "Logic",
    severity: "High",
    pokemonId: 65,
    description: "Poisoning the cache with malicious responses to deliver attacks to all users.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "021",
    name: "Broken Access Control",
    codename: "IDOR",
    type: "Logic",
    severity: "Critical",
    pokemonId: 131,
    description: "Insecure Direct Object References and horizontal/vertical privilege escalation flaws.",
    found: true,
    writeupUrl: "writeups/idor.html"
  },
  {
    id: "022",
    name: "Business Logic Flaws",
    codename: "BizLogic",
    type: "Logic",
    severity: "Medium",
    pokemonId: 97,
    description: "Abusing intended application workflows to perform unintended actions.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "023",
    name: "CORS Misconfiguration",
    codename: "CORS",
    type: "Network",
    severity: "High",
    pokemonId: 57,
    description: "Overly permissive CORS policies allowing unauthorized cross-origin data access.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "024",
    name: "Open Redirect",
    codename: "OpenRedirect",
    type: "Client-Side",
    severity: "Low",
    pokemonId: 145,
    description: "Redirecting users to arbitrary external URLs to facilitate phishing attacks.",
    found: true,
    writeupUrl: "writeups/openredirect.html"
  },
  {
    id: "025",
    name: "Subdomain Takeover",
    codename: "SubTakeover",
    type: "Network",
    severity: "High",
    pokemonId: 144,
    description: "Claiming abandoned subdomains pointing to deprovisioned cloud/SaaS resources.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "026",
    name: "Race Condition",
    codename: "RaceCondition",
    type: "Logic",
    severity: "High",
    pokemonId: 135,
    description: "Exploiting time-of-check to time-of-use gaps to bypass security controls.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "027",
    name: "Client-Side Path Traversal",
    codename: "CSPT",
    type: "Client-Side",
    severity: "High",
    pokemonId: 28,
    description: "Exploiting client-side path handling to access unintended resources or files.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "028",
    name: "LDAP Injection",
    codename: "LDAPi",
    type: "Injection",
    severity: "High",
    pokemonId: 102,
    description: "Injecting LDAP statements to bypass authentication or extract directory data.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "029",
    name: "Mass Assignment",
    codename: "MassAssign",
    type: "Logic",
    severity: "High",
    pokemonId: 143,
    description: "Binding user-supplied data to model objects to modify protected fields.",
    found: false,
    writeupUrl: ""
  },
  {
    id: "030",
    name: "HTTP Parameter Pollution",
    codename: "HPP",
    type: "Logic",
    severity: "Medium",
    pokemonId: 131,
    description: "Injecting duplicate HTTP parameters to confuse server-side logic.",
    found: false,
    writeupUrl: ""
  }
  ,
  {
    id: "031",
    name: "LLM Injection",
    codename: "LLMi",
    type: "Injection",
    severity: "High",
    pokemonId: 200,
    description: "Malicious prompt or data injected into language-model-driven components causing unauthorized actions, data exfiltration, or incorrect outputs.",
    found: false,
    writeupUrl: "writeups/llm-injection.html"
  }
];
